#!/bin/bash
# system monitor

# Color variables
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
magenta='\033[0;35m'
cyan='\033[0;36m'
# Clear the color after that
clear='\033[0m'

echo -e "${green}DISK USAGE${clear}:"
df -h 
echo -e "${cyan}USERS${clear}:"
w
echo -e "${yellow}MEMORY${clear}:"    
grep MemTotal -m /proc/meminfo
echo -e "${blue}RUNNING PROCESSES${clear}:"
ps
echo -e "${magenta}CPU${clear}:"
mpstat
